version: '3'

services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Tarun
    volumes:
      - ./DB_QUERIS:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - springbootnetwork

  backendservice:
    build: ./target
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/shopping_portal?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=Tarun
      - spring.datasource.driver-class-name =com.mysql.jdbc.Driver

    ports:
      - 8085:8085
    networks:
      - springbootnetwork

networks:
  springbootnetwork: